[profile.release]
panic = 'unwind'
split-debuginfo = "unpacked"


[workspace]
members = [
    'node',
	"pallets/kylin-oracle",
	"pallets/crowdloan-rewards",
	"pallets/democracy",
	"runtime/pichiu",
	"runtime/common",
]
