[profile.release]
panic = 'unwind'
split-debuginfo = "unpacked"


[workspace]
members = [
    'node',
	"pallets/kylin-oracle",
	"pallets/kylin-feed",
    # SBP-M1 review: you should remove if not needed
    #"pallets/kylin-market",
	"runtime/pichiu",
	"runtime/kylin",
	"runtime/common",
]
